### ISSUE TITLE
is catch signature correct?

### ISSUE THREAD

**Issue by unional** [typings/typed-es6-promise#1]
https://github.com/typed-typings/npm-es6-promise/blob/master/dist/es6-promise.d.ts#L34

``` ts
function foo() : Promise<Something> {
  return getSomething().catch<Something | void>(err => {
    if (err.code === 'ABC') {
      return;
    }
    throw err;
  });
}
```

Is this how I should use it?
`catch()` may recover the error thus I understand it returns `<U> | thenable<U>`, and with `strictNullCheck` I needs `<Something | void>` to make it valid.

**Comment by blakeembrey** [comment]
It is correct. Using `.catch` would return a new promise so it should also return a new promise type. Your code in `.catch` has a void path (the `return`) so it needs `| void` with strict null checking. It seems it's helping you here.

**Comment by blakeembrey** [comment]
I'm going to close this for now, feel free to continue the discussion 😄
